en:
  Menu1Letters: "1. Letters"
  Menu2Words: "2. Words"
  MenuExit: "Exit"
  Menu: "Menu"
  NotImplemented: "Not Implemented Yet"
  LetterGameWelcome: "Welcome to Letter Morse game!\nPress Enter to start"
  LetterGameStartRoundMessage: "Round {stageNum}.\nWhat letter is it?"
  LetterGameWrongMessage: "Try again.\nAttempt {attemptNum}/3"
  LetterGameFailedMessage: "Wrong.\n Correct answer is \"{currLetter}\".\nIt's code is \"{currCode}\""
  LetterGameEndMessage: "Done. Press Enter to start\nnew game"
ru:
  Menu1Letters: "1. Буквы"
  Menu2Words: "2. Слова"
  MenuExit: "Выйти"
  Menu: "Меню"
  Not Implemented: "В разработке"
  LetterGameWelcome: "Рады видеть в игре на передачу буковок.\nНажмите Enter, чтобы начать"
  LetterGameStartRoundMessage: "Раунд {stageNum}.\nЧто это за буква?"
  LetterGameWrongMessage: "Попробуйте ещё раз.\nПопытка {attemptNum}/3"
  LetterGameFailedMessage: "Неправильно. Это была буква \"{currLetter}\". Её код: {currCode}"
  LetterGameEndMessage: "Конец. Чтобы перезапустить игру\nнажмите Enter"